//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA_X.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAT_BOXS
    {
        public string CHAT_SESSION { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public string CHAT_TIME { get; set; }
    }
}
