//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA_X.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int CONTACT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string MESSAGE { get; set; }
        public string LEVEL { get; set; }
        public string STATUS { get; set; }
        public string LOGIN_TIME { get; set; }
        public string LOGIN_IP { get; set; }
    }
}
