//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA_X.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERAL_POSTS
    {
        public int POST_ID { get; set; }
        public string AUTHOR { get; set; }
        public string TIMELINE_TEXT { get; set; }
        public byte[] TIMELINE_IMAGE { get; set; }
        public string POSTING_TIME { get; set; }
        public string POSTING_STATUS { get; set; }
        public int POST_LIKE { get; set; }
        public int POST_DISLIKE { get; set; }
        public string POST_IP { get; set; }
        public string POST_TAG { get; set; }
    }
}
