//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA_X.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public int NOTE_ID { get; set; }
        public string USERNAME { get; set; }
        public string NOTE_DATE { get; set; }
        public string NOTE_TEXT { get; set; }
        public string STATUS { get; set; }
        public string NOTE_TIME { get; set; }
        public string NOTE_IP { get; set; }
    }
}
